---
title: "Analyzing the results" 
author: "Michael Koch"
date: "07-03-2022"
output: html_document
---

# Working through the results of the Mini- (/ Pilot-) simulation for the SVNP

## Step1: Prepearations

```{r, message = F}
#source required functions & parameters
source('~/1vs2StepBayesianRegSEM/R/functions.R')
source('~/1vs2StepBayesianRegSEM/R/parameters.R')
```

```{r}
# load results
resultsSVNP <- read.csv("~/1vs2StepBayesianRegSEM/output/resultsSVNP.csv", 
                        sep = " ", 
                        header = TRUE)
convSVNP <- read.csv("~/1vs2StepBayesianRegSEM/output/convSVNP.csv",
                     sep = " ",
                     header = TRUE)
```

```{r, chache=T}
# inspect both a bit
head(resultsSVNP)
head(convSVNP)
```

## Select only converged rows of the results

```{r}
#resultsTrimmed <- selectConv(resultsSVNP)
resultsTrimmed <- resultsSVNP # voor nu ff convergence negeren, wordt belangrijk met RHSP
```

## Compute output object based on the converged results

```{r}
outcomes <- computeOutcomes(resultsTrimmed, modelPars)
```

```{r}
head(outcomes)
```



